const mongoose=require("mongoose");

const XeSchema=new mongoose.Schema(
    {
    IDXe:{
        type:String,
        required:true
    },
    BienSo:{
        type:String,
        required:true
    },
    TenXe:{
        type:String,
        required:true
    },
    SoCho:{
        type:Number,
        required:true
    },
    TruyenDong:{
        type:String
    },
    NhienLieu:{
        type:String,
        required:true
    },
    MoTa:{
        type:String,
    },
    SoTien:{
        type:Number,
        required:true
    },
    HinhAnh:{
        type:String,
        required:true
    },
    TinhTrang:{
        type:String,
        required:true,
    },
    IDDon:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"SoXe"
    }
})
const KhachHangSchema=new mongoose.Schema({
    IDKH:{
        type:String,
    },
    TenKH:{
        type:String,
        required:true
    },
    NgaySinh:{
        type:Number,
        required:true
    },
    DiaChi:{
        type:String,
        required:true
    },
    SoDienThoai:{
        type:String,
        required:true
    },
    CMND:{
        type:String,
        required:true
    },
    HinhCMND:{
        type:String,
    },
    BangLai:{
        type:String
    },
    HinhBangLai:{
        type:String
    }
})
const SoXeSchema=new mongoose.Schema({
    IDDon:{
        type:String,
    },
    NgayBatDau:{
        type:Number,
        required:true
    },
    NgayKetThuc:{
        type:Number,
        required:true
    },
    TinhTrang:{
        type:String
    },
    IDXe:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Xe"
    },
    IDKH:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"KhachHang"
    },
})

const TaiKhoanSchema=new mongoose.Schema({
    TenTaiKhoan:{
        type:String,
        required:true
    },
    MatKhau:{
        type:String,
        required:true
    },
    ChucVu:{
        type:String,
        required:true
    },
    IDKH:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"KhachHang"
    },
    IDNV:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"NhanVien"
    },
})
const NhanVienSchema = new mongoose.Schema({
    TenTaiKhoan:{
        type:String,
        required:true
    },
    Avatar:{
        type:String
    },
    TenNV:{
        type:String,
        required:true
    },
    NgaySinh:{
        type:Number,
        required:true
    },
    DiaChi:{
        type:String,
        required:true
    },
    SoDienThoai:{
        type:String,
        required:true
    },
    CMND:{
        type:String,
        required:true
    },
    HinhCMND:{
        type:String,
        required:true
    },
})


let NhanVien=mongoose.model("NhanVien",NhanVienSchema);
let Xe=mongoose.model("Xe",XeSchema);
let KhachHang=mongoose.model("KhachHang",KhachHangSchema);
let SoXe=mongoose.model("SoXe",SoXeSchema);
let TaiKhoan=mongoose.model("TaiKhoan",TaiKhoanSchema);
module.exports={Xe,NhanVien,KhachHang,SoXe,TaiKhoan};